-- Usuario
CREATE TABLE Usuario (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    setor VARCHAR2(255)
);

-- Operador
CREATE TABLE Operador (
    id NUMBER PRIMARY KEY,
    CONSTRAINT fk_operador_usuario FOREIGN KEY (id) REFERENCES Usuario(id)
);

-- Administrador
CREATE TABLE Administrador (
    id NUMBER PRIMARY KEY,
    senha VARCHAR2(255) NOT NULL,
    CONSTRAINT fk_admin_usuario FOREIGN KEY (id) REFERENCES Usuario(id)
);

-- Drone
CREATE TABLE Drone (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR2(50),
    modelo VARCHAR2(100)
);

-- Checklist
CREATE TABLE Checklist (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bateria NUMBER(10,2),
    sensoresFuncionais NUMBER(1),
    drone_id NUMBER,
    CONSTRAINT fk_checklist_drone FOREIGN KEY (drone_id) REFERENCES Drone(id)
);

-- Sensor
CREATE TABLE Sensor (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100),
    drone_id NUMBER,
    CONSTRAINT fk_sensor_drone FOREIGN KEY (drone_id) REFERENCES Drone(id)
);

-- Sensor Temperatura
CREATE TABLE SensorTemperatura (
    id NUMBER PRIMARY KEY,
    temperatura NUMBER(10,2),
    CONSTRAINT fk_temp_sensor FOREIGN KEY (id) REFERENCES Sensor(id)
);

-- Sensor Umidade
CREATE TABLE SensorUmidade (
    id NUMBER PRIMARY KEY,
    umidade NUMBER(10,2),
    CONSTRAINT fk_umidade_sensor FOREIGN KEY (id) REFERENCES Sensor(id)
);

-- Sensor Infravermelho
CREATE TABLE SensorInfravermelho (
    id NUMBER PRIMARY KEY,
    ativo NUMBER(1),
    CONSTRAINT fk_ir_sensor FOREIGN KEY (id) REFERENCES Sensor(id)
);

-- Cadastro Areas
CREATE TABLE CadastroAreas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tamanho NUMBER(10,2),
    localizacao VARCHAR2(255),
    tipoCultivo VARCHAR2(100)
);

-- Missoes de Voo
CREATE TABLE MissoesVoo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idMissao VARCHAR2(50)
);

-- Registro de Dados
CREATE TABLE RegistroDados (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    missao_id NUMBER,
    CONSTRAINT fk_registro_missao FOREIGN KEY (missao_id) REFERENCES MissoesVoo(id)
);

-- Relatorio
CREATE TABLE Relatorio (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicoes NUMBER(10,2),
    qtd_voo NUMBER,
    registro_id NUMBER,
    CONSTRAINT fk_relatorio_registro FOREIGN KEY (registro_id) REFERENCES RegistroDados(id)
);
